// This file is generated by cpp/generate_glue_prototype.js
// Do not edit this file directly

import type { GlueMessageProto } from './glue';

export const GLUE_VERSION = 2;

export const GLUE_MESSAGE_PROTOTYPES: { [name: string]: GlueMessageProto } = {
  "erro_evt": {
    "name": "erro_evt",
    "structName": "glue_msg_error",
    "className": "GlueMsgError",
    "fields": [
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      }
    ]
  },
  "load_req": {
    "name": "load_req",
    "structName": "glue_msg_load_req",
    "className": "GlueMsgLoadReq",
    "fields": [
      {
        "type": "arr_str",
        "name": "model_paths",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "n_ctx_auto",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_mmap",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_mlock",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_webgpu",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_gpu_layers",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "no_perf",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "seed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_threads",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "embeddings",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "offload_kqv",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_batch",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_seq_max",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "pooling_type",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "rope_scaling_type",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "rope_freq_base",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "rope_freq_scale",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_ext_factor",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_attn_factor",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_beta_fast",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "yarn_beta_slow",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "yarn_orig_ctx",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "cache_type_k",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "cache_type_v",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "flash_attn",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "swa_full",
        "isNullable": true
      }
    ]
  },
  "load_res": {
    "name": "load_res",
    "structName": "glue_msg_load_res",
    "className": "GlueMsgLoadRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_batch",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ubatch",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_vocab",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_ctx_train",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_embd",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_layer",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "metadata_key",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "metadata_val",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_bos",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_eos",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_eot",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "list_tokens_eog",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "add_bos_token",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "add_eos_token",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "has_encoder",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token_decoder_start",
        "isNullable": false
      }
    ]
  },
  "opti_req": {
    "name": "opti_req",
    "structName": "glue_msg_set_options_req",
    "className": "GlueMsgSetOptionsReq",
    "fields": [
      {
        "type": "bool",
        "name": "embeddings",
        "isNullable": false
      }
    ]
  },
  "opti_res": {
    "name": "opti_res",
    "structName": "glue_msg_set_options_res",
    "className": "GlueMsgSetOptionsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "sint_req": {
    "name": "sint_req",
    "structName": "glue_msg_sampling_init_req",
    "className": "GlueMsgSamplingInitReq",
    "fields": [
      {
        "type": "int",
        "name": "mirostat",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "mirostat_tau",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "mirostat_eta",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "temp",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "top_p",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "top_k",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "penalty_last_n",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_repeat",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_freq",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "penalty_present",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "dynatemp_range",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "dynatemp_exponent",
        "isNullable": true
      },
      {
        "type": "arr_str",
        "name": "samplers_sequence",
        "isNullable": true
      },
      {
        "type": "str",
        "name": "grammar",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_prev",
        "isNullable": true
      },
      {
        "type": "int",
        "name": "n_probs",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "min_p",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "typical_p",
        "isNullable": true
      },
      {
        "type": "float",
        "name": "typ_p",
        "isNullable": true
      },
      {
        "type": "arr_int",
        "name": "logit_bias_toks",
        "isNullable": true
      },
      {
        "type": "arr_float",
        "name": "logit_bias_vals",
        "isNullable": true
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": true
      }
    ]
  },
  "sint_res": {
    "name": "sint_res",
    "structName": "glue_msg_sampling_init_res",
    "className": "GlueMsgSamplingInitRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "gvoc_req": {
    "name": "gvoc_req",
    "structName": "glue_msg_get_vocab_req",
    "className": "GlueMsgGetVocabReq",
    "fields": []
  },
  "gvoc_res": {
    "name": "gvoc_res",
    "structName": "glue_msg_get_vocab_res",
    "className": "GlueMsgGetVocabRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_raw",
        "name": "vocab",
        "isNullable": false
      }
    ]
  },
  "lkup_req": {
    "name": "lkup_req",
    "structName": "glue_msg_lookup_token_req",
    "className": "GlueMsgLookupTokenReq",
    "fields": [
      {
        "type": "str",
        "name": "piece",
        "isNullable": false
      }
    ]
  },
  "lkup_res": {
    "name": "lkup_res",
    "structName": "glue_msg_lookup_token_res",
    "className": "GlueMsgLookupTokenRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token",
        "isNullable": false
      }
    ]
  },
  "tokn_req": {
    "name": "tokn_req",
    "structName": "glue_msg_tokenize_req",
    "className": "GlueMsgTokenizeReq",
    "fields": [
      {
        "type": "str",
        "name": "text",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "special",
        "isNullable": false
      }
    ]
  },
  "tokn_res": {
    "name": "tokn_res",
    "structName": "glue_msg_tokenize_res",
    "className": "GlueMsgTokenizeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "dtkn_req": {
    "name": "dtkn_req",
    "structName": "glue_msg_detokenize_req",
    "className": "GlueMsgDetokenizeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "dtkn_res": {
    "name": "dtkn_res",
    "structName": "glue_msg_detokenize_res",
    "className": "GlueMsgDetokenizeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "raw",
        "name": "buffer",
        "isNullable": false
      }
    ]
  },
  "deco_req": {
    "name": "deco_req",
    "structName": "glue_msg_decode_req",
    "className": "GlueMsgDecodeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "skip_logits",
        "isNullable": false
      }
    ]
  },
  "deco_res": {
    "name": "deco_res",
    "structName": "glue_msg_decode_res",
    "className": "GlueMsgDecodeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "enco_req": {
    "name": "enco_req",
    "structName": "glue_msg_encode_req",
    "className": "GlueMsgEncodeReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "enco_res": {
    "name": "enco_res",
    "structName": "glue_msg_encode_res",
    "className": "GlueMsgEncodeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      }
    ]
  },
  "ssam_req": {
    "name": "ssam_req",
    "structName": "glue_msg_sampling_sample_req",
    "className": "GlueMsgSamplingSampleReq",
    "fields": []
  },
  "ssam_res": {
    "name": "ssam_res",
    "structName": "glue_msg_sampling_sample_res",
    "className": "GlueMsgSamplingSampleRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "raw",
        "name": "piece",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "token",
        "isNullable": false
      }
    ]
  },
  "sacc_req": {
    "name": "sacc_req",
    "structName": "glue_msg_sampling_accept_req",
    "className": "GlueMsgSamplingAcceptReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sacc_res": {
    "name": "sacc_res",
    "structName": "glue_msg_sampling_accept_res",
    "className": "GlueMsgSamplingAcceptRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "glog_req": {
    "name": "glog_req",
    "structName": "glue_msg_get_logits_req",
    "className": "GlueMsgGetLogitsReq",
    "fields": [
      {
        "type": "int",
        "name": "top_k",
        "isNullable": false
      }
    ]
  },
  "glog_res": {
    "name": "glog_res",
    "structName": "glue_msg_get_logits_res",
    "className": "GlueMsgGetLogitsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      },
      {
        "type": "arr_float",
        "name": "probs",
        "isNullable": false
      }
    ]
  },
  "gemb_req": {
    "name": "gemb_req",
    "structName": "glue_msg_get_embeddings_req",
    "className": "GlueMsgGetEmbeddingsReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "gemb_res": {
    "name": "gemb_res",
    "structName": "glue_msg_get_embeddings_res",
    "className": "GlueMsgGetEmbeddingsRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "arr_float",
        "name": "embeddings",
        "isNullable": false
      }
    ]
  },
  "kvcr_req": {
    "name": "kvcr_req",
    "structName": "glue_msg_get_kv_remove_req",
    "className": "GlueMsgGetKvRemoveReq",
    "fields": [
      {
        "type": "int",
        "name": "n_keep",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_discard",
        "isNullable": false
      }
    ]
  },
  "kvcr_res": {
    "name": "kvcr_res",
    "structName": "glue_msg_get_kv_remove_res",
    "className": "GlueMsgGetKvRemoveRes",
    "fields": [
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "kvcc_req": {
    "name": "kvcc_req",
    "structName": "glue_msg_get_kv_clear_req",
    "className": "GlueMsgGetKvClearReq",
    "fields": []
  },
  "kvcc_res": {
    "name": "kvcc_res",
    "structName": "glue_msg_get_kv_clear_res",
    "className": "GlueMsgGetKvClearRes",
    "fields": [
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "sesa_req": {
    "name": "sesa_req",
    "structName": "glue_msg_session_save_req",
    "className": "GlueMsgSessionSaveReq",
    "fields": [
      {
        "type": "str",
        "name": "session_path",
        "isNullable": false
      }
    ]
  },
  "sesa_res": {
    "name": "sesa_res",
    "structName": "glue_msg_session_save_res",
    "className": "GlueMsgSessionSaveRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sesl_req": {
    "name": "sesl_req",
    "structName": "glue_msg_session_load_req",
    "className": "GlueMsgSessionLoadReq",
    "fields": [
      {
        "type": "str",
        "name": "session_path",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "sesl_res": {
    "name": "sesl_res",
    "structName": "glue_msg_session_load_res",
    "className": "GlueMsgSessionLoadRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "stat_req": {
    "name": "stat_req",
    "structName": "glue_msg_status_req",
    "className": "GlueMsgStatusReq",
    "fields": []
  },
  "stat_res": {
    "name": "stat_res",
    "structName": "glue_msg_status_res",
    "className": "GlueMsgStatusRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "pctx_req": {
    "name": "pctx_req",
    "structName": "glue_msg_perf_context_req",
    "className": "GlueMsgPerfContextReq",
    "fields": []
  },
  "pctx_res": {
    "name": "pctx_res",
    "structName": "glue_msg_perf_context_res",
    "className": "GlueMsgPerfContextRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_start_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_load_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_p_eval_ms",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "t_eval_ms",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_p_eval",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_eval",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_reused",
        "isNullable": false
      }
    ]
  },
  "prst_req": {
    "name": "prst_req",
    "structName": "glue_msg_perf_reset_req",
    "className": "GlueMsgPerfResetReq",
    "fields": []
  },
  "prst_res": {
    "name": "prst_res",
    "structName": "glue_msg_perf_reset_res",
    "className": "GlueMsgPerfResetRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      }
    ]
  },
  "tben_req": {
    "name": "tben_req",
    "structName": "glue_msg_test_benchmark_req",
    "className": "GlueMsgTestBenchmarkReq",
    "fields": [
      {
        "type": "str",
        "name": "type",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_samples",
        "isNullable": false
      }
    ]
  },
  "tben_res": {
    "name": "tben_res",
    "structName": "glue_msg_test_benchmark_res",
    "className": "GlueMsgTestBenchmarkRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "t_ms",
        "isNullable": false
      }
    ]
  },
  "tper_req": {
    "name": "tper_req",
    "structName": "glue_msg_test_perplexity_req",
    "className": "GlueMsgTestPerplexityReq",
    "fields": [
      {
        "type": "arr_int",
        "name": "tokens",
        "isNullable": false
      }
    ]
  },
  "tper_res": {
    "name": "tper_res",
    "structName": "glue_msg_test_perplexity_res",
    "className": "GlueMsgTestPerplexityRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "ppl",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "nll",
        "isNullable": false
      },
      {
        "type": "float",
        "name": "cross_entropy",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "t_ms",
        "isNullable": false
      }
    ]
  },
  "cfmt_req": {
    "name": "cfmt_req",
    "structName": "glue_msg_chat_format_req",
    "className": "GlueMsgChatFormatReq",
    "fields": [
      {
        "type": "str",
        "name": "tmpl",
        "isNullable": true
      },
      {
        "type": "bool",
        "name": "add_ass",
        "isNullable": true
      },
      {
        "type": "arr_str",
        "name": "roles",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "contents",
        "isNullable": false
      }
    ]
  },
  "cfmt_res": {
    "name": "cfmt_res",
    "structName": "glue_msg_chat_format_res",
    "className": "GlueMsgChatFormatRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "formatted_chat",
        "isNullable": false
      }
    ]
  },
  "mtmd_req": {
    "name": "mtmd_req",
    "structName": "glue_msg_load_mmproj_or_mtmd_context_req",
    "className": "GlueMsgLoadMmprojOrMtmdContextReq",
    "fields": [
      {
        "type": "arr_str",
        "name": "mmproj_paths",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "use_gpu",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_threads",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "print_timings",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "warmup",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "load_audio",
        "isNullable": false
      }
    ]
  },
  "mtmd_res": {
    "name": "mtmd_res",
    "structName": "glue_msg_load_mmproj_or_mtmd_context_res",
    "className": "GlueMsgLoadMmprojOrMtmdContextRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "supports_vision",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "supports_image",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "supports_audio",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_sample_rate",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "media_marker",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "projector_split_loading_strategy",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "projector_split_loading_status",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "projector_split_paths",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "projector_split_tensor_counts",
        "isNullable": false
      },
      {
        "type": "arr_bool",
        "name": "projector_split_position_embeddings_present",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "projector_split_position_embedding_tensor_names",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "projector_split_position_embedding_cols",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "projector_split_position_embedding_rows",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "projector_split_position_embedding_planes",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "projector_split_inventory_errors",
        "isNullable": false
      }
    ]
  },
  "mediareq": {
    "name": "mediareq",
    "structName": "glue_msg_load_media_bytes_req",
    "className": "GlueMsgLoadMediaBytesReq",
    "fields": [
      {
        "type": "raw",
        "name": "media_bytes",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "media_id",
        "isNullable": false
      }
    ]
  },
  "mediares": {
    "name": "mediares",
    "structName": "glue_msg_load_media_bytes_res",
    "className": "GlueMsgLoadMediaBytesRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "media_index",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_media",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "media_byte_length",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "detected_media_format",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_detected",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_target_sample_rate",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_output_channels",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_decoder_init_result",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_decoder_init_result_description",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_decoder_length_result",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_decoder_length_result_description",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_decoder_length_available",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_decoder_frame_count",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_decoder_length_unreliable",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_planned_pcm_samples",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_planned_pcm_allocation_bytes",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_actual_pcm_allocation_bytes",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_max_pcm_allocation_bytes",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_allocation_exceeds_limit",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_chunked_decode_used",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_read_reached_end",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "audio_decoder_read_result",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_decoder_read_result_description",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_frames_read",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_pcm_resize_succeeded",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "audio_bitmap_init_succeeded",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "audio_decode_failure_stage",
        "isNullable": false
      }
    ]
  },
  "mtok_req": {
    "name": "mtok_req",
    "structName": "glue_msg_mtmd_tokenize_req",
    "className": "GlueMsgMtmdTokenizeReq",
    "fields": [
      {
        "type": "str",
        "name": "text",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "add_special",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "parse_special",
        "isNullable": false
      }
    ]
  },
  "mtok_res": {
    "name": "mtok_res",
    "structName": "glue_msg_mtmd_tokenize_res",
    "className": "GlueMsgMtmdTokenizeRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_chunks",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_tokens",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_pos",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vocab_size",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "text_token_bounds_passed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "text_token_out_of_range_total",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_projector_type",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "vision_projector_type_name",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "vision_position_blocker_kind",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "vision_position_embeddings_available",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_cols",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_rows",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_planes",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "image_position_bounds_passed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "image_position_out_of_range_total",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_types",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_n_tokens",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_n_pos",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_token_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_token_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_first_negative_token",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_first_over_vocab_token",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_out_of_range_count",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_n_tokens",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_n_pos",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_image_nx",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_image_ny",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_t_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_t_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_x_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_x_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_y_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_y_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_z_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_z_max",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "chunk_vision_position_blocker_kind",
        "isNullable": false
      },
      {
        "type": "arr_bool",
        "name": "chunk_vision_position_bounds_applicable",
        "isNullable": false
      },
      {
        "type": "arr_bool",
        "name": "chunk_vision_position_bounds_passed",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_out_of_range_count",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_embedding_row_limit",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_pos_x_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_pos_y_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_input_nx_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_input_ny_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_patch_size",
        "isNullable": false
      }
    ]
  },
  "mevl_req": {
    "name": "mevl_req",
    "structName": "glue_msg_mtmd_eval_chunks_req",
    "className": "GlueMsgMtmdEvalChunksReq",
    "fields": [
      {
        "type": "bool",
        "name": "logits_last",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_batch",
        "isNullable": false
      }
    ]
  },
  "mevl_res": {
    "name": "mevl_res",
    "structName": "glue_msg_mtmd_eval_chunks_res",
    "className": "GlueMsgMtmdEvalChunksRes",
    "fields": [
      {
        "type": "bool",
        "name": "success",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "message",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "n_past",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vocab_size",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "text_token_bounds_passed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "text_token_out_of_range_total",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_projector_type",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "vision_projector_type_name",
        "isNullable": false
      },
      {
        "type": "str",
        "name": "vision_position_blocker_kind",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "vision_position_embeddings_available",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_cols",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_rows",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "vision_position_embedding_planes",
        "isNullable": false
      },
      {
        "type": "bool",
        "name": "image_position_bounds_passed",
        "isNullable": false
      },
      {
        "type": "int",
        "name": "image_position_out_of_range_total",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_types",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_n_tokens",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_n_pos",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_token_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_token_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_first_negative_token",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_first_over_vocab_token",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_text_out_of_range_count",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_n_tokens",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_n_pos",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_image_nx",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_image_ny",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_t_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_t_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_x_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_x_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_y_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_y_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_z_min",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_media_decoder_pos_z_max",
        "isNullable": false
      },
      {
        "type": "arr_str",
        "name": "chunk_vision_position_blocker_kind",
        "isNullable": false
      },
      {
        "type": "arr_bool",
        "name": "chunk_vision_position_bounds_applicable",
        "isNullable": false
      },
      {
        "type": "arr_bool",
        "name": "chunk_vision_position_bounds_passed",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_out_of_range_count",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_embedding_row_limit",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_pos_x_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_pos_y_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_input_nx_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_input_ny_max",
        "isNullable": false
      },
      {
        "type": "arr_int",
        "name": "chunk_vision_position_patch_size",
        "isNullable": false
      }
    ]
  }
};

// struct glue_msg_error
export interface GlueMsgError {
  _name: "erro_evt";
  message: string;
}

// struct glue_msg_load_req
export interface GlueMsgLoadReq {
  _name: "load_req";
  model_paths: string[];
  n_ctx_auto: boolean;
  use_mmap: boolean;
  use_mlock: boolean;
  use_webgpu: boolean;
  n_gpu_layers: number;
  no_perf: boolean;
  seed: number;
  n_ctx: number;
  n_threads: number;
  embeddings?: boolean | undefined;
  offload_kqv?: boolean | undefined;
  n_batch?: number | undefined;
  n_seq_max?: number | undefined;
  pooling_type?: string | undefined;
  rope_scaling_type?: string | undefined;
  rope_freq_base?: number | undefined;
  rope_freq_scale?: number | undefined;
  yarn_ext_factor?: number | undefined;
  yarn_attn_factor?: number | undefined;
  yarn_beta_fast?: number | undefined;
  yarn_beta_slow?: number | undefined;
  yarn_orig_ctx?: number | undefined;
  cache_type_k?: string | undefined;
  cache_type_v?: string | undefined;
  flash_attn?: boolean | undefined;
  swa_full?: boolean | undefined;
}

// struct glue_msg_load_res
export interface GlueMsgLoadRes {
  _name: "load_res";
  success: boolean;
  n_ctx: number;
  n_batch: number;
  n_ubatch: number;
  n_vocab: number;
  n_ctx_train: number;
  n_embd: number;
  n_layer: number;
  metadata_key: string[];
  metadata_val: string[];
  token_bos: number;
  token_eos: number;
  token_eot: number;
  list_tokens_eog: number[];
  add_bos_token: boolean;
  add_eos_token: boolean;
  has_encoder: boolean;
  token_decoder_start: number;
}

// struct glue_msg_set_options_req
export interface GlueMsgSetOptionsReq {
  _name: "opti_req";
  embeddings: boolean;
}

// struct glue_msg_set_options_res
export interface GlueMsgSetOptionsRes {
  _name: "opti_res";
  success: boolean;
}

// struct glue_msg_sampling_init_req
export interface GlueMsgSamplingInitReq {
  _name: "sint_req";
  mirostat?: number | undefined;
  mirostat_tau?: number | undefined;
  mirostat_eta?: number | undefined;
  temp?: number | undefined;
  top_p?: number | undefined;
  top_k?: number | undefined;
  penalty_last_n?: number | undefined;
  penalty_repeat?: number | undefined;
  penalty_freq?: number | undefined;
  penalty_present?: number | undefined;
  dynatemp_range?: number | undefined;
  dynatemp_exponent?: number | undefined;
  samplers_sequence?: string[] | undefined;
  grammar?: string | undefined;
  n_prev?: number | undefined;
  n_probs?: number | undefined;
  min_p?: number | undefined;
  typical_p?: number | undefined;
  typ_p?: number | undefined;
  logit_bias_toks?: number[] | undefined;
  logit_bias_vals?: number[] | undefined;
  tokens?: number[] | undefined;
}

// struct glue_msg_sampling_init_res
export interface GlueMsgSamplingInitRes {
  _name: "sint_res";
  success: boolean;
}

// struct glue_msg_get_vocab_req
export interface GlueMsgGetVocabReq {
  _name: "gvoc_req";
}

// struct glue_msg_get_vocab_res
export interface GlueMsgGetVocabRes {
  _name: "gvoc_res";
  success: boolean;
  vocab: Uint8Array[];
}

// struct glue_msg_lookup_token_req
export interface GlueMsgLookupTokenReq {
  _name: "lkup_req";
  piece: string;
}

// struct glue_msg_lookup_token_res
export interface GlueMsgLookupTokenRes {
  _name: "lkup_res";
  success: boolean;
  token: number;
}

// struct glue_msg_tokenize_req
export interface GlueMsgTokenizeReq {
  _name: "tokn_req";
  text: string;
  special: boolean;
}

// struct glue_msg_tokenize_res
export interface GlueMsgTokenizeRes {
  _name: "tokn_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_detokenize_req
export interface GlueMsgDetokenizeReq {
  _name: "dtkn_req";
  tokens: number[];
}

// struct glue_msg_detokenize_res
export interface GlueMsgDetokenizeRes {
  _name: "dtkn_res";
  success: boolean;
  buffer: Uint8Array;
}

// struct glue_msg_decode_req
export interface GlueMsgDecodeReq {
  _name: "deco_req";
  tokens: number[];
  skip_logits: boolean;
}

// struct glue_msg_decode_res
export interface GlueMsgDecodeRes {
  _name: "deco_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_encode_req
export interface GlueMsgEncodeReq {
  _name: "enco_req";
  tokens: number[];
}

// struct glue_msg_encode_res
export interface GlueMsgEncodeRes {
  _name: "enco_res";
  success: boolean;
  message: string;
  n_past: number;
}

// struct glue_msg_sampling_sample_req
export interface GlueMsgSamplingSampleReq {
  _name: "ssam_req";
}

// struct glue_msg_sampling_sample_res
export interface GlueMsgSamplingSampleRes {
  _name: "ssam_res";
  success: boolean;
  piece: Uint8Array;
  token: number;
}

// struct glue_msg_sampling_accept_req
export interface GlueMsgSamplingAcceptReq {
  _name: "sacc_req";
  tokens: number[];
}

// struct glue_msg_sampling_accept_res
export interface GlueMsgSamplingAcceptRes {
  _name: "sacc_res";
  success: boolean;
}

// struct glue_msg_get_logits_req
export interface GlueMsgGetLogitsReq {
  _name: "glog_req";
  top_k: number;
}

// struct glue_msg_get_logits_res
export interface GlueMsgGetLogitsRes {
  _name: "glog_res";
  success: boolean;
  tokens: number[];
  probs: number[];
}

// struct glue_msg_get_embeddings_req
export interface GlueMsgGetEmbeddingsReq {
  _name: "gemb_req";
  tokens: number[];
}

// struct glue_msg_get_embeddings_res
export interface GlueMsgGetEmbeddingsRes {
  _name: "gemb_res";
  success: boolean;
  message: string;
  embeddings: number[];
}

// struct glue_msg_get_kv_remove_req
export interface GlueMsgGetKvRemoveReq {
  _name: "kvcr_req";
  n_keep: number;
  n_discard: number;
}

// struct glue_msg_get_kv_remove_res
export interface GlueMsgGetKvRemoveRes {
  _name: "kvcr_res";
  n_past: number;
  success: boolean;
}

// struct glue_msg_get_kv_clear_req
export interface GlueMsgGetKvClearReq {
  _name: "kvcc_req";
}

// struct glue_msg_get_kv_clear_res
export interface GlueMsgGetKvClearRes {
  _name: "kvcc_res";
  n_past: number;
  success: boolean;
}

// struct glue_msg_session_save_req
export interface GlueMsgSessionSaveReq {
  _name: "sesa_req";
  session_path: string;
}

// struct glue_msg_session_save_res
export interface GlueMsgSessionSaveRes {
  _name: "sesa_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_session_load_req
export interface GlueMsgSessionLoadReq {
  _name: "sesl_req";
  session_path: string;
  tokens: number[];
}

// struct glue_msg_session_load_res
export interface GlueMsgSessionLoadRes {
  _name: "sesl_res";
  success: boolean;
}

// struct glue_msg_status_req
export interface GlueMsgStatusReq {
  _name: "stat_req";
}

// struct glue_msg_status_res
export interface GlueMsgStatusRes {
  _name: "stat_res";
  success: boolean;
  tokens: number[];
}

// struct glue_msg_perf_context_req
export interface GlueMsgPerfContextReq {
  _name: "pctx_req";
}

// struct glue_msg_perf_context_res
export interface GlueMsgPerfContextRes {
  _name: "pctx_res";
  success: boolean;
  t_start_ms: number;
  t_load_ms: number;
  t_p_eval_ms: number;
  t_eval_ms: number;
  n_p_eval: number;
  n_eval: number;
  n_reused: number;
}

// struct glue_msg_perf_reset_req
export interface GlueMsgPerfResetReq {
  _name: "prst_req";
}

// struct glue_msg_perf_reset_res
export interface GlueMsgPerfResetRes {
  _name: "prst_res";
  success: boolean;
}

// struct glue_msg_test_benchmark_req
export interface GlueMsgTestBenchmarkReq {
  _name: "tben_req";
  type: string;
  n_samples: number;
}

// struct glue_msg_test_benchmark_res
export interface GlueMsgTestBenchmarkRes {
  _name: "tben_res";
  success: boolean;
  message: string;
  t_ms: number;
}

// struct glue_msg_test_perplexity_req
export interface GlueMsgTestPerplexityReq {
  _name: "tper_req";
  tokens: number[];
}

// struct glue_msg_test_perplexity_res
export interface GlueMsgTestPerplexityRes {
  _name: "tper_res";
  success: boolean;
  message: string;
  ppl: number;
  nll: number;
  cross_entropy: number;
  n_tokens: number;
  t_ms: number;
}

// struct glue_msg_chat_format_req
export interface GlueMsgChatFormatReq {
  _name: "cfmt_req";
  tmpl?: string | undefined;
  add_ass?: boolean | undefined;
  roles: string[];
  contents: string[];
}

// struct glue_msg_chat_format_res
export interface GlueMsgChatFormatRes {
  _name: "cfmt_res";
  success: boolean;
  message: string;
  formatted_chat: string;
}

// struct glue_msg_load_mmproj_or_mtmd_context_req
export interface GlueMsgLoadMmprojOrMtmdContextReq {
  _name: "mtmd_req";
  mmproj_paths: string[];
  use_gpu: boolean;
  n_threads: number;
  print_timings: boolean;
  warmup: boolean;
  load_audio: boolean;
}

// struct glue_msg_load_mmproj_or_mtmd_context_res
export interface GlueMsgLoadMmprojOrMtmdContextRes {
  _name: "mtmd_res";
  success: boolean;
  message: string;
  supports_vision: boolean;
  supports_image: boolean;
  supports_audio: boolean;
  audio_sample_rate: number;
  media_marker: string;
  projector_split_loading_strategy: string;
  projector_split_loading_status: string;
  projector_split_paths: string[];
  projector_split_tensor_counts: number[];
  projector_split_position_embeddings_present: boolean[];
  projector_split_position_embedding_tensor_names: string[];
  projector_split_position_embedding_cols: number[];
  projector_split_position_embedding_rows: number[];
  projector_split_position_embedding_planes: number[];
  projector_split_inventory_errors: string[];
}

// struct glue_msg_load_media_bytes_req
export interface GlueMsgLoadMediaBytesReq {
  _name: "mediareq";
  media_bytes: Uint8Array;
  media_id: string;
}

// struct glue_msg_load_media_bytes_res
export interface GlueMsgLoadMediaBytesRes {
  _name: "mediares";
  success: boolean;
  message: string;
  media_index: number;
  n_media: number;
  media_byte_length: number;
  detected_media_format: string;
  audio_detected: boolean;
  audio_target_sample_rate: number;
  audio_output_channels: number;
  audio_decoder_init_result: number;
  audio_decoder_init_result_description: string;
  audio_decoder_length_result: number;
  audio_decoder_length_result_description: string;
  audio_decoder_length_available: boolean;
  audio_decoder_frame_count: string;
  audio_decoder_length_unreliable: boolean;
  audio_planned_pcm_samples: string;
  audio_planned_pcm_allocation_bytes: string;
  audio_actual_pcm_allocation_bytes: string;
  audio_max_pcm_allocation_bytes: string;
  audio_allocation_exceeds_limit: boolean;
  audio_chunked_decode_used: boolean;
  audio_read_reached_end: boolean;
  audio_decoder_read_result: number;
  audio_decoder_read_result_description: string;
  audio_frames_read: string;
  audio_pcm_resize_succeeded: boolean;
  audio_bitmap_init_succeeded: boolean;
  audio_decode_failure_stage: string;
}

// struct glue_msg_mtmd_tokenize_req
export interface GlueMsgMtmdTokenizeReq {
  _name: "mtok_req";
  text: string;
  add_special: boolean;
  parse_special: boolean;
}

// struct glue_msg_mtmd_tokenize_res
export interface GlueMsgMtmdTokenizeRes {
  _name: "mtok_res";
  success: boolean;
  message: string;
  n_chunks: number;
  n_tokens: number;
  n_pos: number;
  vocab_size: number;
  text_token_bounds_passed: boolean;
  text_token_out_of_range_total: number;
  vision_projector_type: number;
  vision_projector_type_name: string;
  vision_position_blocker_kind: string;
  vision_position_embeddings_available: boolean;
  vision_position_embedding_cols: number;
  vision_position_embedding_rows: number;
  vision_position_embedding_planes: number;
  image_position_bounds_passed: boolean;
  image_position_out_of_range_total: number;
  chunk_types: number[];
  chunk_n_tokens: number[];
  chunk_n_pos: number[];
  chunk_text_token_min: number[];
  chunk_text_token_max: number[];
  chunk_text_first_negative_token: number[];
  chunk_text_first_over_vocab_token: number[];
  chunk_text_out_of_range_count: number[];
  chunk_media_n_tokens: number[];
  chunk_media_n_pos: number[];
  chunk_image_nx: number[];
  chunk_image_ny: number[];
  chunk_media_decoder_pos_t_min: number[];
  chunk_media_decoder_pos_t_max: number[];
  chunk_media_decoder_pos_x_min: number[];
  chunk_media_decoder_pos_x_max: number[];
  chunk_media_decoder_pos_y_min: number[];
  chunk_media_decoder_pos_y_max: number[];
  chunk_media_decoder_pos_z_min: number[];
  chunk_media_decoder_pos_z_max: number[];
  chunk_vision_position_blocker_kind: string[];
  chunk_vision_position_bounds_applicable: boolean[];
  chunk_vision_position_bounds_passed: boolean[];
  chunk_vision_position_out_of_range_count: number[];
  chunk_vision_position_embedding_row_limit: number[];
  chunk_vision_position_pos_x_max: number[];
  chunk_vision_position_pos_y_max: number[];
  chunk_vision_position_input_nx_max: number[];
  chunk_vision_position_input_ny_max: number[];
  chunk_vision_position_patch_size: number[];
}

// struct glue_msg_mtmd_eval_chunks_req
export interface GlueMsgMtmdEvalChunksReq {
  _name: "mevl_req";
  logits_last: boolean;
  n_batch: number;
}

// struct glue_msg_mtmd_eval_chunks_res
export interface GlueMsgMtmdEvalChunksRes {
  _name: "mevl_res";
  success: boolean;
  message: string;
  n_past: number;
  vocab_size: number;
  text_token_bounds_passed: boolean;
  text_token_out_of_range_total: number;
  vision_projector_type: number;
  vision_projector_type_name: string;
  vision_position_blocker_kind: string;
  vision_position_embeddings_available: boolean;
  vision_position_embedding_cols: number;
  vision_position_embedding_rows: number;
  vision_position_embedding_planes: number;
  image_position_bounds_passed: boolean;
  image_position_out_of_range_total: number;
  chunk_types: number[];
  chunk_n_tokens: number[];
  chunk_n_pos: number[];
  chunk_text_token_min: number[];
  chunk_text_token_max: number[];
  chunk_text_first_negative_token: number[];
  chunk_text_first_over_vocab_token: number[];
  chunk_text_out_of_range_count: number[];
  chunk_media_n_tokens: number[];
  chunk_media_n_pos: number[];
  chunk_image_nx: number[];
  chunk_image_ny: number[];
  chunk_media_decoder_pos_t_min: number[];
  chunk_media_decoder_pos_t_max: number[];
  chunk_media_decoder_pos_x_min: number[];
  chunk_media_decoder_pos_x_max: number[];
  chunk_media_decoder_pos_y_min: number[];
  chunk_media_decoder_pos_y_max: number[];
  chunk_media_decoder_pos_z_min: number[];
  chunk_media_decoder_pos_z_max: number[];
  chunk_vision_position_blocker_kind: string[];
  chunk_vision_position_bounds_applicable: boolean[];
  chunk_vision_position_bounds_passed: boolean[];
  chunk_vision_position_out_of_range_count: number[];
  chunk_vision_position_embedding_row_limit: number[];
  chunk_vision_position_pos_x_max: number[];
  chunk_vision_position_pos_y_max: number[];
  chunk_vision_position_input_nx_max: number[];
  chunk_vision_position_input_ny_max: number[];
  chunk_vision_position_patch_size: number[];
}


export type GlueMsg = GlueMsgError | GlueMsgLoadReq | GlueMsgLoadRes | GlueMsgSetOptionsReq | GlueMsgSetOptionsRes | GlueMsgSamplingInitReq | GlueMsgSamplingInitRes | GlueMsgGetVocabReq | GlueMsgGetVocabRes | GlueMsgLookupTokenReq | GlueMsgLookupTokenRes | GlueMsgTokenizeReq | GlueMsgTokenizeRes | GlueMsgDetokenizeReq | GlueMsgDetokenizeRes | GlueMsgDecodeReq | GlueMsgDecodeRes | GlueMsgEncodeReq | GlueMsgEncodeRes | GlueMsgSamplingSampleReq | GlueMsgSamplingSampleRes | GlueMsgSamplingAcceptReq | GlueMsgSamplingAcceptRes | GlueMsgGetLogitsReq | GlueMsgGetLogitsRes | GlueMsgGetEmbeddingsReq | GlueMsgGetEmbeddingsRes | GlueMsgGetKvRemoveReq | GlueMsgGetKvRemoveRes | GlueMsgGetKvClearReq | GlueMsgGetKvClearRes | GlueMsgSessionSaveReq | GlueMsgSessionSaveRes | GlueMsgSessionLoadReq | GlueMsgSessionLoadRes | GlueMsgStatusReq | GlueMsgStatusRes | GlueMsgPerfContextReq | GlueMsgPerfContextRes | GlueMsgPerfResetReq | GlueMsgPerfResetRes | GlueMsgTestBenchmarkReq | GlueMsgTestBenchmarkRes | GlueMsgTestPerplexityReq | GlueMsgTestPerplexityRes | GlueMsgChatFormatReq | GlueMsgChatFormatRes | GlueMsgLoadMmprojOrMtmdContextReq | GlueMsgLoadMmprojOrMtmdContextRes | GlueMsgLoadMediaBytesReq | GlueMsgLoadMediaBytesRes | GlueMsgMtmdTokenizeReq | GlueMsgMtmdTokenizeRes | GlueMsgMtmdEvalChunksReq | GlueMsgMtmdEvalChunksRes;
